USE locadora_db;
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tb_funcionario ADD
	telefone varchar(MAX) NULL,
	endereco varchar(MAX) NULL
GO
ALTER TABLE dbo.tb_funcionario SET (LOCK_ESCALATION = TABLE)
GO
COMMIT